### ISSUE TITLE
Add-on is not working if deluge-plugin 'Label' is switched off

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kharts/deluge-xbmc-plugin#3]
```
If Deluge plugin 'Label' is not enabled this xbmc add-on does not work.
due to several Python-Script-Error: KeyError: ('label',)
```

Original issue reported on code.google.com by `roman.mu...@gmail.com` on 26 May 2013 at 4:24

Attachments:
* [err.txt](https://storage.googleapis.com/google-code-attachments/deluge-xbmc-plugin/issue-3/comment-0/err.txt)

**Comment by kharts** [comment]
Fixed in master
